In [1]:
from spacy_utils import *

C:\pythonenvironments\DataAndAi\Lib\site-packages\spacy\util.py:910: UserWarning: [W095] Model 'en_core_web_sm' (3.7.1) was trained with spaCy v3.7.2 and may not be 100% compatible with the current version (3.8.2). If you see errors or degraded performance, download a newer compatible model or retrain your custom model with the current spaCy version. For more details and available updates, run: python -m spacy validate
  warnings.warn(warn_msg)

In [2]:
# Create Spacy document
doc_ai_forecast2 = create_doc('../text_data/ai_forecast2.txt')

In [3]:
# Get tokenization, POS, and grammatical structure
print("Tokenization, POS, and Grammatical Structure for ai_forecast2.txt:")
tokenization_pos_df = get_tokenization_and_pos(doc_ai_forecast2)
tokenization_pos_df

Tokenization, POS, and Grammatical Structure for ai_forecast2.txt:

,SENTENCE,WORD,POS,DEP,DEP_ON,POS_EXPLAIN,DEP_EXPLAIN
0,The global artificial intelligence market size...,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,The,DET,det,size,determiner,determiner
2,NaN,global,ADJ,amod,size,adjective,adjectival modifier
3,NaN,artificial,ADJ,amod,size,adjective,adjectival modifier
4,NaN,intelligence,NOUN,compound,market,noun,compound
...,...,...,...,...,...,...,...
1775,NaN,sale,NOUN,pobj,from,noun,object of preposition
1776,NaN,of,ADP,prep,sale,adposition,prepositional modifier
1777,NaN,AI,PROPN,compound,products,proper noun,compound
1778,NaN,products,NOUN,pobj,of,noun,object of preposition
1779,NaN,and,CCONJ,cc,is,coordinating conjunction,coordinating conjunction

In [4]:
# Get named entities
print("\nNamed Entities for ai_forecast2.txt:")
named_entities_df = get_named_entities(doc_ai_forecast2)
named_entities_df

Named Entities for ai_forecast2.txt:

                        Entity    Label
0                $93.5 billion    MONEY
1                         2021     DATE
2    Grand View Research, Inc.      ORG
3                       annual     DATE
4                        38.1%  PERCENT
..                         ...      ...
96                     Chinese     NORP
97                  April 2018     DATE
98                          AI      ORG
99                          AI      ORG
100                         AI      ORG

[101 rows x 2 columns]

In [5]:
# Explain POS and dependency tags
print("\nExplanation of POS and Dependency Tags for ai_forecast2.txt:")
tags_explanation_df = explain_tags(doc_ai_forecast2)
tags_explanation_df

Explanation of POS and Dependency Tags for ai_forecast2.txt:

,Token,POS,POS Explanation,Dependency,Dependency Explanation
0,The,DET,determiner,det,determiner
1,global,ADJ,adjective,amod,adjectival modifier
2,artificial,ADJ,adjective,amod,adjectival modifier
3,intelligence,NOUN,noun,compound,compound
4,market,NOUN,noun,compound,compound
...,...,...,...,...,...
1708,sale,NOUN,noun,pobj,object of preposition
1709,of,ADP,adposition,prep,prepositional modifier
1710,AI,PROPN,proper noun,compound,compound
1711,products,NOUN,noun,pobj,object of preposition
1712,and,CCONJ,coordinating conjunction,cc,coordinating conjunction

In [13]:
# Define individual patterns
pattern_ai = {"ArtificialIntelligence": [{"LOWER": "artificial"}, {"LOWER": "intelligence"}]}
pattern_ai_verb = {"AIVerb": [{"LOWER": "ai"}, {"POS": "VERB"}]}
pattern_number_percent = {"NumberPercent": [{"LIKE_NUM": True}, {"TEXT": "%"}]}
pattern_company_name = {"CompanyName": [{"POS": "PROPN"}]}

In [7]:
matches_ai = find_matches(doc_ai_forecast2, pattern_ai)
matches_ai

                      Match  Start   End
0   artificial intelligence      2     4
1   Artificial intelligence     96    98
2   artificial intelligence    161   163
3   Artificial Intelligence    363   365
4   Artificial Intelligence    453   455
5   artificial intelligence    465   467
6   Artificial Intelligence    637   639
7   artificial intelligence    788   790
8   Artificial Intelligence   1240  1242
9   artificial intelligence   1368  1370
10  artificial intelligence   1447  1449
11  artificial intelligence   1600  1602

In [8]:
matches_ai_verb = find_matches(doc_ai_forecast2, pattern_ai_verb)
matches_ai_verb

     Match  Start   End
0  AI grew   1071  1073

In [9]:
matches_number_percent = find_matches(doc_ai_forecast2, pattern_number_percent)
matches_number_percent

   Match  Start   End
0  38.1%     37    39
1    66%    198   200
2   115%   1257  1259
3    42%   1402  1404

In [10]:
matches_company_name = find_matches(doc_ai_forecast2, pattern_company_name)
matches_company_name

        Match  Start   End
0       Grand     16    17
1        View     17    18
2    Research     18    19
3        Inc.     20    21
4        CAGR     34    35
..        ...    ...   ...
130      Inc.   1608  1609
131     April   1617  1618
132        AI   1657  1658
133        AI   1667  1668
134        AI   1710  1711

[135 rows x 3 columns]